### PR TITLE
Merge remaining sr1_knut_dev things, fix testswarnings

### PR DESCRIPTION
**Pull request by JelleAalbers**
This merges the remaining commits from sr1_knut_dev into master. I could not resist a few slight changes to the formatting. @kdund could you have a brief look to check I didn't destroy anything accidentally? 

This also fixes using non-tuples for indexing (deprecated in numpy) and a failing test for bestfit_minuit.

### CODE REVIEW

**Comment by JelleAalbers** [comment]
@kdund Any chance of having a look at this?

**Comment by JelleAalbers** [comment]
@kdund I would propose merging this, blueice will break for future numpy versions otherwise. Minuit support is likely already broken without this. Plus, your improvements deserve to make it into master :-)

I had a look through it, this will:
  * Add support for the 'efficiency_name' source config option. This specifies the name of the parameter controlling the efficiency for that source. Sources not specifying efficiency_name are controlled by the likelihood-global 'efficiency' option (as before).
  * Removes the deprecated LogLikelihood class, which already gave DeprecationWarnings for a long time. (One should use UnbinnedLogLikelihood)
  * Allow weighting of the summed likelihoods in LogLikelihoodSum -- see its docstring
  * Fix processing of minuit arguments (likely this worked only for old versions of minuit).
  * Fix deprecated (in numpy 1.15, July 2018) use of non-tuples for indexing in pdf_morphers.

**Comment by kdund** [comment]
That'd be great-- I am unaccountably locked out of midway atm, once I am back I can confirm if it works on my side at least
(Setting a reminder)

**Comment by kdund** [comment]
Back on midway! 
Yes, I'm happy to merge it now (is that my button to push?)

**Pull request merged**
